(function(){
	angular
		.module('vMapsApp')
		.service('rolesConfig', function(){
            return {               
            baseUrl:  'http://176.37.101.48:3000/',
            loginUrl: 'login.json',
            itemsUrl:	'testJson.json',
            demoJSON: {
                topLayers: ['otb_lom_ar3', 'sc144_lom_ar3', 'otbb_lom_ar3'],
                loadFirst: [
					'ar3_area_otb',
                    'cross_lom_ar3',
                    'fig8_lom_ar3',
                    'ofc12_lom_ar3',
                    'ofc48_lom_ar3',
                    'ofc144_lom_ar3',
                    'otb_lom_ar3',
                    'otbb_lom_ar3',
                    'sc_lom_ar3',
                    'sc_48_lom_ar3',
                    'sc_144_lom_ar3'
                ],
                fig8_lom_ar1: {
                    name: 'fig8_lom_ar1',
                    className: 'fig8_lom_ar1',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/fig8_lom_ar1',
                    color: '#FFD600',
                    fillColor: '#FFD600',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				fig8_lom_ar2: {
                    name: 'fig8_lom_ar2',
                    className: 'fig8_lom_ar2',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/fig8_lom_ar2',
                    color: '#FFD600',
                    fillColor: '#FFD600',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				fig8_lom_ar3: {
                    name: 'fig8_lom_ar3',
                    className: 'fig8_lom_ar3',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/fig8_lom_ar3',
                    color: '#FFD600',
                    fillColor: '#FFD600',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				fig8_lom_ar5: {
                    name: 'fig8_lom_ar5',
                    className: 'fig8_lom_ar5',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/fig8_lom_ar5',
                    color: '#FFD600',
                    fillColor: '#FFD600',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },    
                ofc12_lom_ar1: {
                    name: 'ofc12_lom_ar1',
                    className: 'ofc12_lom_ar1',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/ofc12_lom_ar1',
                    color: '#00B0FF',
                    fillColor: '#00B0FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				ofc12_lom_ar2: {
                    name: 'ofc12_lom_ar2',
                    className: 'ofc12_lom_ar2',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/ofc12_lom_ar2',
                    color: '#00B0FF',
                    fillColor: '#00B0FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				ofc12_lom_ar3: {
                    name: 'ofc12_lom_ar3',
                    className: 'ofc12_lom_ar3',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/ofc12_lom_ar3',
                    color: '#00B0FF',
                    fillColor: '#00B0FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				ofc12_lom_ar5: {
                    name: 'ofc12_lom_ar5',
                    className: 'ofc12_lom_ar5',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/ofc12_lom_ar5',
                    color: '#00B0FF',
                    fillColor: '#00B0FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                ofc48_lom_ar1: {
                    name: 'ofc48_lom_ar1',
                    className: 'ofc48_lom_ar1',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/ofc48_lom_ar1',
                    color: '#BF360C ',
                    fillColor: '#BF360C ',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.5,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				ofc48_lom_ar2: {
                    name: 'ofc48_lom_ar2',
                    className: 'ofc48_lom_ar2',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/ofc48_lom_ar2',
                    color: '#BF360C ',
                    fillColor: '#BF360C ',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.5,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				ofc48_lom_ar3: {
                    name: 'ofc48_lom_ar3',
                    className: 'ofc48_lom_ar3',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/ofc48_lom_ar3',
                    color: '#BF360C ',
                    fillColor: '#BF360C ',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.5,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				ofc48_lom_ar5: {
                    name: 'ofc48_lom_ar5',
                    className: 'ofc48_lom_ar5',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/ofc48_lom_ar5',
                    color: '#BF360C ',
                    fillColor: '#BF360C ',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 2.5,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'comment',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'planed_installation_week'
	                ],
                    category: 'ofc',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                ofc144_lom_ar1: {
                    name: 'ofc144_lom_ar1',
                    className: 'ofc144_lom_ar1',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/ofc144_lom_ar1',
                    color: '#1A237E',
                    fillColor: '#1A237E',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 3.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'Planned_Installation_Week'
	                ],
                    category: 'ofc',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				ofc144_lom_ar2: {
                    name: 'ofc144_lom_ar2',
                    className: 'ofc144_lom_ar2',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/ofc144_lom_ar2',
                    color: '#1A237E',
                    fillColor: '#1A237E',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 3.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'Planned_Installation_Week'
	                ],
                    category: 'ofc',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				ofc144_lom_ar3: {
                    name: 'ofc144_lom_ar3',
                    className: 'ofc144_lom_ar3',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/ofc144_lom_ar3',
                    color: '#1A237E',
                    fillColor: '#1A237E',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 3.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'Planned_Installation_Week'
	                ],
                    category: 'ofc',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				ofc144_lom_ar5: {
                    name: 'ofc144_lom_ar5',
                    className: 'ofc144_lom_ar5',
                    pane: 'overlayPane',
                    type: 'line',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/ofc144_lom_ar5',
                    color: '#1A237E',
                    fillColor: '#1A237E',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 3.0,
                    popupColumns: [
                        'id', 
                        'osp_cable_name', 
                        'osp_cable_installation_date', 
                        'osp_cable_template',
                        'marker_start',
                        'marker_stop', 
                        'cable_lenght', 
                        'id_prov', 
                        'Planned_Installation_Week'
	                ],
                    category: 'ofc',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                otb_lom_ar1: {
                    name: 'otb_lom_ar1',
                    className: 'otb_lom_ar1',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/otb_lom_ar1',
                    color: '#ccc',
                    fillColor: '#00E5FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				otb_lom_ar2: {
                    name: 'otb_lom_ar2',
                    className: 'otb_lom_ar2',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/otb_lom_ar2',
                    color: '#ccc',
                    fillColor: '#00E5FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				otb_lom_ar3: {
                    name: 'otb_lom_ar3',
                    className: 'otb_lom_ar3',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/otb_lom_ar3',
                    color: '#ccc',
                    fillColor: '#00E5FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				otb_lom_ar5: {
                    name: 'otb_lom_ar5',
                    className: 'otb_lom_ar5',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/otb_lom_ar5',
                    color: '#ccc',
                    fillColor: '#00E5FF',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                otbb_lom_ar1: {
                    name: 'otbb_lom_ar1',
                    className: 'otbb_lom_ar1',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/otbb_lom_ar1',
                    color: '#666',
                    fillColor: '#D500F9',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				otbb_lom_ar2: {
                    name: 'otbb_lom_ar2',
                    className: 'otbb_lom_ar2',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/otbb_lom_ar2',
                    color: '#666',
                    fillColor: '#D500F9',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				otbb_lom_ar3: {
                    name: 'otbb_lom_ar3',
                    className: 'otbb_lom_ar3',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/otbb_lom_ar3',
                    color: '#666',
                    fillColor: '#D500F9',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				otbb_lom_ar5: {
                    name: 'otbb_lom_ar5',
                    className: 'otbb_lom_ar5',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/otbb_lom_ar5',
                    color: '#666',
                    fillColor: '#D500F9',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 4,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type',
                        'location_id',
                        'otb_name', 
                        'otb_serial_number', 
                        'otb_installation_date',
                        'otb_template', 
                        'splitter_1_serial_number', 
                        'splitter_2_serial_number', 
                        'latitude', 
                        'longitude', 
                        'trunk_attachement', 
                        'comment',
                        'id_prov'
	                ],
                    category: 'otb_lines',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                sc_lom_ar1: {
                    name: 'sc_lom_ar1',
                    className: 'sc_lom_ar1',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/sc_lom_ar1',
                    color: '#333333',
                    fillColor: '#067c4e',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'name'
	                ],
                    category: 'sc_points',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				sc_lom_ar2: {
                    name: 'sc_lom_ar2',
                    className: 'sc_lom_ar2',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/sc_lom_ar2',
                    color: '#333333',
                    fillColor: '#067c4e',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'name'
	                ],
                    category: 'sc_points',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				sc_lom_ar3: {
                    name: 'sc_lom_ar3',
                    className: 'sc_lom_ar3',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/sc_lom_ar3',
                    color: '#333333',
                    fillColor: '#067c4e',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'name'
	                ],
                    category: 'sc_points',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				sc_lom_ar5: {
                    name: 'sc_lom_ar5',
                    className: 'sc_lom_ar5',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/sc_lom_ar5',
                    color: '#333333',
                    fillColor: '#067c4e',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'name'
	                ],
                    category: 'sc_points',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                sc_48_lom_ar1: {
                    name: 'sc_48_lom_ar1',
                    className: 'sc_48_lom_ar1',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/sc_48_lom_ar1',
                    color: '#333333',
                    fillColor: '#C0392B',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				sc_48_lom_ar2: {
                    name: 'sc_48_lom_ar2',
                    className: 'sc_48_lom_ar2',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/sc_48_lom_ar2',
                    color: '#333333',
                    fillColor: '#C0392B',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				sc_48_lom_ar3: {
                    name: 'sc_48_lom_ar3',
                    className: 'sc_48_lom_ar3',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/sc_48_lom_ar3',
                    color: '#333333',
                    fillColor: '#C0392B',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				sc_48_lom_ar5: {
                    name: 'sc_48_lom_ar5',
                    className: 'sc_48_lom_ar5',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/sc_48_lom_ar5',
                    color: '#333333',
                    fillColor: '#C0392B',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                sc_144_lom_ar1: {
                    name: 'sc_144_lom_ar1',
                    className: 'sc_144_lom_ar1',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/sc_144_lom_ar1',
                    color: '#333333',
                    fillColor: '#19459d',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				sc_144_lom_ar2: {
                    name: 'sc_144_lom_ar2',
                    className: 'sc_144_lom_ar2',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/sc_144_lom_ar2',
                    color: '#333333',
                    fillColor: '#19459d',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				sc_144_lom_ar3: {
                    name: 'sc_144_lom_ar3',
                    className: 'sc_144_lom_ar3',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/sc_144_lom_ar3',
                    color: '#333333',
                    fillColor: '#19459d',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				sc_144_lom_ar5: {
                    name: 'sc_144_lom_ar5',
                    className: 'sc_144_lom_ar5',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/sc_144_lom_ar5',
                    color: '#333333',
                    fillColor: '#19459d',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id', 
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'splice_closure_name', 
                        'splice_closure_serial_number', 
                        'splice_closure_installation_dat', 
                        'splice_closure_template', 
                        'comment', 
                        'latitude', 
                        'longitude', 
                        'id_prov'
	                ],
                    category: 'sc_points',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                poles_lom_ar1: {
                    name: 'poles_lom_ar1',
                    className: 'poles_lom_ar1',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/poles_lom_ar1',
                    color: '#666',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'district', 
                        'neighbourhood', 
                        'longitude', 
                        'latitude', 
                        'comment', 
                        'nature_du_support', 
                        'anarchie_accroche_cable', 
                        'transfo', 
                        'geometrie_du_poteau', 
                        'transition_aero_souterraine', 
                        'commentaires_etats_du_poteaux', 
                        'poteau_inaccessible', 
                        'prise_de_terre', 
                        'id_poste', 
                        'etat_du_poteau', 
                        'type', 
                        'osp_isp', 
                        'commentaires', 
                        'hauteur_de_lelement_le_plus_ba', 
                        'hauteur_poteau_hors_sol', 
                        'type_reseau_electrique', 
                        'surved', 
                        'realise_par'
	                ],
                    category: 'other',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				poles_lom_ar2: {
                    name: 'poles_lom_ar2',
                    className: 'poles_lom_ar2',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/poles_lom_ar2',
                    color: '#666',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'district', 
                        'neighbourhood', 
                        'longitude', 
                        'latitude', 
                        'comment', 
                        'nature_du_support', 
                        'anarchie_accroche_cable', 
                        'transfo', 
                        'geometrie_du_poteau', 
                        'transition_aero_souterraine', 
                        'commentaires_etats_du_poteaux', 
                        'poteau_inaccessible', 
                        'prise_de_terre', 
                        'id_poste', 
                        'etat_du_poteau', 
                        'type', 
                        'osp_isp', 
                        'commentaires', 
                        'hauteur_de_lelement_le_plus_ba', 
                        'hauteur_poteau_hors_sol', 
                        'type_reseau_electrique', 
                        'surved', 
                        'realise_par'
	                ],
                    category: 'other',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				poles_lom_ar3: {
                    name: 'poles_lom_ar3',
                    className: 'poles_lom_ar3',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/poles_lom_ar3',
                    color: '#666',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'district', 
                        'neighbourhood', 
                        'longitude', 
                        'latitude', 
                        'comment', 
                        'nature_du_support', 
                        'anarchie_accroche_cable', 
                        'transfo', 
                        'geometrie_du_poteau', 
                        'transition_aero_souterraine', 
                        'commentaires_etats_du_poteaux', 
                        'poteau_inaccessible', 
                        'prise_de_terre', 
                        'id_poste', 
                        'etat_du_poteau', 
                        'type', 
                        'osp_isp', 
                        'commentaires', 
                        'hauteur_de_lelement_le_plus_ba', 
                        'hauteur_poteau_hors_sol', 
                        'type_reseau_electrique', 
                        'surved', 
                        'realise_par'
	                ],
                    category: 'other',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				poles_lom_ar5: {
                    name: 'poles_lom_ar5',
                    className: 'poles_lom_ar5',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/poles_lom_ar5',
                    color: '#666',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'city_region', 
                        'location_type', 
                        'location_id', 
                        'district', 
                        'neighbourhood', 
                        'longitude', 
                        'latitude', 
                        'comment', 
                        'nature_du_support', 
                        'anarchie_accroche_cable', 
                        'transfo', 
                        'geometrie_du_poteau', 
                        'transition_aero_souterraine', 
                        'commentaires_etats_du_poteaux', 
                        'poteau_inaccessible', 
                        'prise_de_terre', 
                        'id_poste', 
                        'etat_du_poteau', 
                        'type', 
                        'osp_isp', 
                        'commentaires', 
                        'hauteur_de_lelement_le_plus_ba', 
                        'hauteur_poteau_hors_sol', 
                        'type_reseau_electrique', 
                        'surved', 
                        'realise_par'
	                ],
                    category: 'other',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                demand_lom_ar1: {
                    name: 'demand_lom_ar1',
                    className: 'demand_lom_ar1',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/demand_lom_ar1',
                    color: '#757575',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id',
                        'otb_city_region',
                        'otb_name',
                        'internal_floors',
                        'comment',
                        'connected'
	                ],
                    category: 'other',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				demand_lom_ar2: {
                    name: 'demand_lom_ar2',
                    className: 'demand_lom_ar2',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/demand_lom_ar2',
                    color: '#757575',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id',
                        'otb_city_region',
                        'otb_name',
                        'internal_floors',
                        'comment',
                        'connected'
	                ],
                    category: 'other',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				demand_lom_ar3: {
                    name: 'demand_lom_ar3',
                    className: 'demand_lom_ar3',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/demand_lom_ar3',
                    color: '#757575',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id',
                        'otb_city_region',
                        'otb_name',
                        'internal_floors',
                        'comment',
                        'connected'
	                ],
                    category: 'other',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				demand_lom_ar5: {
                    name: 'demand_lom_ar5',
                    className: 'demand_lom_ar5',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/demand_lom_ar5',
                    color: '#757575',
                    fillColor: '#757575',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id',
                        'otb_city_region',
                        'otb_name',
                        'internal_floors',
                        'comment',
                        'connected'
	                ],
                    category: 'other',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                ar1_area_otb: {
                    name: 'ar1_area_otb',
                    className: 'ar1_area_otb',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/ar1_area_otb',
                    color: '#33691E',
                    fillColor: '#33691E',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id, otb_name',
                        'id_provisoire',
                        'campo2',
                        'status',
                        'comments',
                        'mq'
	                ],
                    category: 'otb_lines',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				ar2_area_otb: {
                    name: 'ar2_area_otb',
                    className: 'ar2_area_otb',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/ar2_area_otb',
                    color: '#33691E',
                    fillColor: '#33691E',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id, otb_name',
                        'id_provisoire',
                        'campo2',
                        'status',
                        'comments',
                        'mq'
	                ],
                    category: 'otb_lines',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				ar3_area_otb: {
                    name: 'ar3_area_otb',
                    className: 'ar3_area_otb',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/ar3_area_otb',
                    color: '#33691E',
                    fillColor: '#33691E',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id, otb_name',
                        'id_provisoire',
                        'campo2',
                        'status',
                        'comments',
                        'mq'
	                ],
                    category: 'otb_lines',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				ar5_area_otb: {
                    name: 'ar5_area_otb',
                    className: 'ar5_area_otb',
                    pane: 'overlayPane',
                    type: 'poly',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/ar5_area_otb',
                    color: '#33691E',
                    fillColor: '#33691E',
                    opacity: 1,
                    fillOpacity: 0.3,
                    weight: 1.0,
                    popupColumns: [
                        'id, otb_name',
                        'id_provisoire',
                        'campo2',
                        'status',
                        'comments',
                        'mq'
	                ],
                    category: 'otb_lines',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
                cross_lom_ar1: {
                    name: 'cross_lom_ar1',
                    className: 'cross_lom_ar1',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar1_lom/cross_lom_ar1',
                    color: '#666',
                    fillColor: '#D50000',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'Storage_loop_metres'
	                ],
                    category: 'other',
                    schema: 'ar1_lom',
                    zone: 'Arrondissement_1'
                },
				cross_lom_ar2: {
                    name: 'cross_lom_ar2',
                    className: 'cross_lom_ar2',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar2_lom/cross_lom_ar2',
                    color: '#666',
                    fillColor: '#D50000',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'Storage_loop_metres'
	                ],
                    category: 'other',
                    schema: 'ar2_lom',
                    zone: 'Arrondissement_2'
                },
				cross_lom_ar3: {
                    name: 'cross_lom_ar3',
                    className: 'cross_lom_ar3',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar3_lom/cross_lom_ar3',
                    color: '#666',
                    fillColor: '#D50000',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'Storage_loop_metres'
	                ],
                    category: 'other',
                    schema: 'ar3_lom',
                    zone: 'Arrondissement_3'
                },
				cross_lom_ar5: {
                    name: 'cross_lom_ar5',
                    className: 'cross_lom_ar5',
                    pane: 'overlayPane',
                    type: 'point',
                    url: 'http://176.37.101.48:3000/bbox/ar5_lom/cross_lom_ar5',
                    color: '#666',
                    fillColor: '#D50000',
                    opacity: 1,
                    fillOpacity: 1,
                    weight: 1.0,
                    radius: 3,
                    popupColumns: [
                        'id',
                        'Storage_loop_metres'
	                ],
                    category: 'other',
                    schema: 'ar5_lom',
                    zone: 'Arrondissement_5'
                },
            },            
            demoLayers: {
                cross_lom_ar1: 'cross_lom_ar1',
				cross_lom_ar2: 'cross_lom_ar2',
				cross_lom_ar3: 'cross_lom_ar3',
				cross_lom_ar5: 'cross_lom_ar5',
				otb_lom_ar1: 'otb_lom_ar1',
				otb_lom_ar2: 'otb_lom_ar2',
				otb_lom_ar3: 'otb_lom_ar3',
				otb_lom_ar5: 'otb_lom_ar5',
                otbb_lom_ar1: 'otbb_lom_ar1',
				otbb_lom_ar2: 'otbb_lom_ar2',
				otbb_lom_ar3: 'otbb_lom_ar3',
				otbb_lom_ar5: 'otbb_lom_ar5',
                sc_lom_ar1: 'sc_lom_ar1',
				sc_lom_ar2: 'sc_lom_ar2',
				sc_lom_ar3: 'sc_lom_ar3',
				sc_lom_ar5: 'sc_lom_ar5',
                sc_144_lom_ar1: 'sc_144_lom_ar1',
				sc_144_lom_ar2: 'sc_144_lom_ar2',
				sc_144_lom_ar3: 'sc_144_lom_ar3',
				sc_144_lom_ar5: 'sc_144_lom_ar5',
                sc_48_lom_ar1: 'sc_48_lom_ar1',
				sc_48_lom_ar2: 'sc_48_lom_ar2',
				sc_48_lom_ar3: 'sc_48_lom_ar33',
				sc_48_lom_ar5: 'sc_48_lom_ar5',
                fig8_lom_ar1: 'fig8_lom_ar1',
				fig8_lom_ar2: 'fig8_lom_ar2',
				fig8_lom_ar3: 'fig8_lom_ar3',
				fig8_lom_ar5: 'fig8_lom_ar5',
				ofc12_lom_ar1: 'ofc12_lom_ar1',
				ofc12_lom_ar2: 'ofc12_lom_ar2',
				ofc12_lom_ar3: 'ofc12_lom_ar3',
				ofc48_lom_ar1: 'ofc48_lom_ar1',
				ofc48_lom_ar2: 'ofc48_lom_ar2',
				ofc48_lom_ar3: 'ofc48_lom_ar3',
				ofc48_lom_ar5: 'ofc48_lom_ar5',
				ofc144_lom_ar1: 'ofc144_lom_ar1',
				ofc144_lom_ar2: 'ofc144_lom_ar2',
				ofc144_lom_ar3: 'ofc144_lom_ar3',
				ofc144_lom_ar5: 'ofc144_lom_ar5',
                poles_lom_ar1: 'poles_lom_ar1',
				poles_lom_ar2: 'poles_lom_ar2',
				poles_lom_ar3: 'poles_lom_ar3',
				poles_lom_ar5: 'poles_lom_ar5',
				ar1_area_otb: 'ar1_area_otb',
				ar2_area_otb: 'ar2_area_otb',
				ar3_area_otb: 'ar3_area_otb',
				ar5_area_otb: 'ar5_area_otb',
				demand_lom_ar1: 'demand_lom_ar1',
				demand_lom_ar2: 'demand_lom_ar2',
				demand_lom_ar3: 'demand_lom_ar3',
				demand_lom_ar5: 'demand_lom_ar5'
            },            
            cityLocation: {
                Lome: {
                    lng: 1.240906,
					lat: 6.130398
                },
                Tabligbo: {
                    lng: 1.502488,
					lat: 6.595080, 
                },
                Kara: {
                    lng: 1.194402,
					lat: 9.552551 
                }
            }		
        }   

	})
}());